#
# Makefile
# ACS Component Code Generator
# Created Alexis Tejeda 27/06/2010
# Updated
#

ANT=ant
RM=rm

all: clean install

install:
	$(ANT) -f src/build.xml install

clean:
	$(ANT) -f src/build.xml clean
